# frozen_string_literal: true

require_relative 'insns/base'
require_relative 'insns/putobject'
require_relative 'insns/putnil'
require_relative 'insns/leave'
require_relative 'insns/opt_plus'
require_relative 'insns/opt_minus'
require_relative 'insns/opt_mult'
require_relative 'insns/opt_div'
require_relative 'insns/getlocal'
require_relative 'insns/setlocal'
require_relative 'insns/dup'
require_relative 'insns/branchunless'
require_relative 'insns/jump'
require_relative 'insns/definemethod'
require_relative 'insns/putself'
require_relative 'insns/opt_lt'
require_relative 'insns/opt_send_without_block'
